### PR TITLE
Migrate spec to new repo fixes #1

### LINKED ISSUE #1: Migrate specifications from old repo
We migrate specification content into this repo with the following process:

- [ ]   clone the specifications repo
- [ ]   clone the bb-payments repo alongside
- [ ]   delete "starter structure" from the spec folder
- [ ]   copy the structure from the specification repo building-blocks/information-mediator folder into the new location in specs
- [ ]   (manually) rebuild the summary.md contents file
- [ ]   create /spec/.gitbook/assets
- [ ]   copy the correct assets in from the specifications repo. I created `grep assets *.md | sed -En 's/^.*\]\((.*)\).*$/\1/p' | sed -E 's/[<|>]//g' | while read x; do cp /Users/rlawson/sites/specifications/building-blocks/information-mediation/$x .gitbook/assets/; done`
- [ ]   search/replace across all md files for ../../.gitbook with .gitbook as the folder is now next to the markdown files, not folders above

### PR DESCRIPTION
**Pull request by rachellawson**
## Description

Migrate the specifications from the old repo here, following steps in #1

### CODE REVIEW

**Comment by rachellawson** [comment]
As per other INITIAL PRs into the per-bb spec, we cannot view the results of this PR until there is at least the beginnings of a structure defined to import into GitBook. So, testing this PR involves checking that 

- [ ] It contains a SUMMARY.md
- [ ] It contains a README.md
- [ ] It only adds files to the /spec folder

**Review by mcarlson — CHANGES_REQUESTED** [review]
Also, there are a number of files that have been deleted instead of renamed with `git mv` this is dangerous as it corrupts the change history. Is there a way to finesse this?

**Review by mcarlson — COMMENTED** [review]
Should 1-version-history.md be deleted?

**Comment by rachellawson** [comment]
> 

The PR is to copy the AS IS content from the single specifications repo at version 0.9.0 to the distributed repos ready fro the next version(s). So, we should not make changes here, only copy.

**Comment by rachellawson** [comment]
> Also, there are a number of files that have been deleted instead of renamed with git mv this is dangerous as it corrupts the change history. Is there a way to finesse this?

Again, because this is a copy of the files from another repo to _replace_ the "default" content we have in the template, it makes no sense to try and create a history as, in effect, it wouldn't be a true reflection, anyway.

All we need to do is ensure that the content of /spec matches the content off the completely separate GovStackWorkingGroup/specifications repo's /building-blocks/Payments folder

**Comment by rachellawson** [comment]
> Should 1-version-history.md be deleted?

Yes - it is not a page in the original for this bb

**Review by mcarlson — APPROVED** [review]

**Pull request merged**
